version: '3.8'

services:

  ewd_nginx:
    image: nginx:1.22
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: unless-stopped
    volumes:
      - ./public:/var/www/app/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ewd_app
      - ewd_db
    networks:
      - ewd-front
      - vw-digital-proxy

  ewd_app:
    image: ${COMPOSE_PROJECT_NAME}_app
    container_name: ${COMPOSE_PROJECT_NAME}_app
    restart: unless-stopped
    build:
      context: ./docker/php
      target: php_81
      args:
        - APP_ENV=${APP_ENV}
    volumes:
      - .:/var/www/app
    depends_on:
      - ewd_db
    networks:
      - ewd-front
      - vw-digital-proxy
      - ewd-back

  ewd_db:
    image: mariadb:10.9.3
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: unless-stopped
    volumes:
      - ./docker/data/db:/var/lib/mysql
      - ./docker/db/data:/home
      - ./var/backups:/var/backups
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Paris
      - LANG=C.UTF-8
    networks:
      - ewd-back

  ewd_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: unless-stopped
    depends_on:
      - ewd_db
    environment:
      - PMA_HOST=ewd_db
    networks:
      - ewd-front
      - ewd-back
      - vw-digital-proxy

  ewd_cron:
    image: ${COMPOSE_PROJECT_NAME}_cron
    container_name: ${COMPOSE_PROJECT_NAME}_cron
    restart: unless-stopped
    build:
      context: ./docker/php
      target: php_81_cron
      args:
        - APP_ENV=${APP_ENV}
    volumes:
      - .:/var/www/app
    depends_on:
      - ewd_db
    networks:
      - ewd-back

  ewd_yarn:
    image: node:18.10
    container_name: ${COMPOSE_PROJECT_NAME}_yarn
    profiles: [ 'yarn' ]
    tty: true
    volumes:
      - .:/app:delegated
    networks:
      - ewd-back
    command: bash -c "cd /app && yarn && yarn build"

networks:
  ewd-front:
  ewd-back:
  vw-digital-proxy:
    external: true
